CREATE MEMORY TABLE PUBLIC.user(
id INTEGER IDENTITY NOT NULL PRIMARY KEY,
name VARCHAR(16),
password VARCHAR(32), 
status INTEGER,
email VARCHAR(100),
tel VARCHAR(100),
qqmsn VARCHAR(100),
gmt_created TIMESTAMP,
gmt_modified TIMESTAMP
);

CREATE MEMORY TABLE PUBLIC.game(
id INTEGER IDENTITY NOT NULL PRIMARY KEY,
user_name VARCHAR(16),
name VARCHAR(100),
start_time TIMESTAMP,
server_name VARCHAR(100), 
url VARCHAR(200),
category VARCHAR(100),
gift_name VARCHAR(100),
platform VARCHAR(100),
gmt_created TIMESTAMP,
gmt_modified TIMESTAMP
);

SET DATABASE REFERENTIAL INTEGRITY FALSE;