-- MySQL Script generated by MySQL Workbench
-- 08/17/14 19:49:20
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kfcms_db
-- -----------------------------------------------------
-- kan kai fu database
DROP SCHEMA IF EXISTS `kfcms_db` ;
CREATE SCHEMA IF NOT EXISTS `kfcms_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `kfcms_db` ;

-- -----------------------------------------------------
-- Table `kfcms_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfcms_db`.`user` ;

CREATE TABLE IF NOT EXISTS `kfcms_db`.`user` (
  `id` INT(20) NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(16) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `tel` VARCHAR(100) NULL,
  `im` VARCHAR(100) NULL,
  `status` TINYINT(1) NULL DEFAULT 0,
  `gmt_created` DATETIME NULL,
  `gmt_modified` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kfcms_db`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfcms_db`.`company` ;

CREATE TABLE IF NOT EXISTS `kfcms_db`.`company` (
  `id` INT(20) NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(16) NOT NULL,
  `name` VARCHAR(200) NULL,
  `platform` VARCHAR(100) NULL,
  `website` VARCHAR(100) NULL,
  `contact_name` VARCHAR(45) NULL,
  `contact_position` VARCHAR(45) NULL,
  `contact_tel` VARCHAR(100) NULL,
  `gmt_created` DATETIME NULL,
  `gmt_modified` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Member Table';


-- -----------------------------------------------------
-- Table `kfcms_db`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfcms_db`.`game` ;

CREATE TABLE IF NOT EXISTS `kfcms_db`.`game` (
  `id` INT(20) NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(16) NOT NULL,
  `name` VARCHAR(45) NULL,
  `start_time` DATETIME NULL,
  `server_name` VARCHAR(100) NULL,
  `url` VARCHAR(200) NULL,
  `category` VARCHAR(45) NULL,
  `platform` VARCHAR(100) NULL,
  `status` TINYINT(1) NULL DEFAULT 0,
  `gmt_created` DATETIME NULL,
  `gmt_modified` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kfcms_db`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfcms_db`.`admin` ;

CREATE TABLE IF NOT EXISTS `kfcms_db`.`admin` (
  `id` INT(20) NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(16) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `gmt_created` DATETIME NULL,
  `gmt_modified` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Admin';


-- -----------------------------------------------------
-- Table `kfcms_db`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfcms_db`.`news` ;

CREATE TABLE IF NOT EXISTS `kfcms_db`.`news` (
  `id` INT(20) NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(16) NOT NULL,
  `category` TINYINT(1) NOT NULL,
  `title` VARCHAR(100) NULL,
  `content` TEXT NULL,
  `status` TINYINT(1) NULL DEFAULT 0,
  `gmt_created` DATETIME NULL,
  `gmt_modified` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
