package com.kfcms.model;
// default package
// Generated Jul 27, 2014 11:32:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int id;
	private String userName;
	private String name;
	private String platform;
	private String website;
	private String contactName;
	private String contactPosition;
	private String contactTel;
	private Date gmtCreated;
	private Date gmtModified;

	public Company() {
	}

	public Company(int id) {
		this.id = id;
	}

	public Company(int id, String userName, String name, String platform,
			String website, String contactName, String contactPosition,
			String contactTel, Date gmtCreated, Date gmtModified) {
		this.id = id;
		this.userName = userName;
		this.name = name;
		this.platform = platform;
		this.website = website;
		this.contactName = contactName;
		this.contactPosition = contactPosition;
		this.contactTel = contactTel;
		this.gmtCreated = gmtCreated;
		this.gmtModified = gmtModified;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPlatform() {
		return this.platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getContactPosition() {
		return this.contactPosition;
	}

	public void setContactPosition(String contactPosition) {
		this.contactPosition = contactPosition;
	}

	public String getContactTel() {
		return this.contactTel;
	}

	public void setContactTel(String contactTel) {
		this.contactTel = contactTel;
	}

	public Date getGmtCreated() {
		return this.gmtCreated;
	}

	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	public Date getGmtModified() {
		return this.gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

}
