package com.kfcms.model;
// default package
// Generated Jul 25, 2014 10:39:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private int companyId;
	private String userName;
	private String companyName;
	private String companyPlatform;
	private String companyWebsite;
	private String contactName;
	private String contactPosition;
	private String contactTel;
	private Date gmtCreated;
	private Date gmtModified;

	public Company() {
	}

	public Company(int companyId) {
		this.companyId = companyId;
	}

	public Company(int companyId, String userName, String companyName,
			String companyPlatform, String companyWebsite, String contactName,
			String contactPosition, String contactTel, Date gmtCreated,
			Date gmtModified) {
		this.companyId = companyId;
		this.userName = userName;
		this.companyName = companyName;
		this.companyPlatform = companyPlatform;
		this.companyWebsite = companyWebsite;
		this.contactName = contactName;
		this.contactPosition = contactPosition;
		this.contactTel = contactTel;
		this.gmtCreated = gmtCreated;
		this.gmtModified = gmtModified;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCompanyPlatform() {
		return this.companyPlatform;
	}

	public void setCompanyPlatform(String companyPlatform) {
		this.companyPlatform = companyPlatform;
	}

	public String getCompanyWebsite() {
		return this.companyWebsite;
	}

	public void setCompanyWebsite(String companyWebsite) {
		this.companyWebsite = companyWebsite;
	}

	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getContactPosition() {
		return this.contactPosition;
	}

	public void setContactPosition(String contactPosition) {
		this.contactPosition = contactPosition;
	}

	public String getContactTel() {
		return this.contactTel;
	}

	public void setContactTel(String contactTel) {
		this.contactTel = contactTel;
	}

	public Date getGmtCreated() {
		return this.gmtCreated;
	}

	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	public Date getGmtModified() {
		return this.gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

}
