package com.kfcms.model;
// default package
// Generated Jul 27, 2014 11:32:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Game generated by hbm2java
 */
public class Game implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String userName;
	private String name;
	private Date startTime;
	private String serverName;
	private String url;
	private String category;
	private String giftName;
	private String platform;
	private Date gmtCreated;
	private Date gmtModified;

	public Game() {
	}

	public Game(String userName, String name, Date startTime,
			String serverName, String url, String category, String giftName,
			String platform, Date gmtCreated, Date gmtModified) {
		this.userName = userName;
		this.name = name;
		this.startTime = startTime;
		this.serverName = serverName;
		this.url = url;
		this.category = category;
		this.giftName = giftName;
		this.platform = platform;
		this.gmtCreated = gmtCreated;
		this.gmtModified = gmtModified;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public String getServerName() {
		return this.serverName;
	}

	public void setServerName(String serverName) {
		this.serverName = serverName;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getGiftName() {
		return this.giftName;
	}

	public void setGiftName(String giftName) {
		this.giftName = giftName;
	}

	public String getPlatform() {
		return this.platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	public Date getGmtCreated() {
		return this.gmtCreated;
	}

	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	public Date getGmtModified() {
		return this.gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

}
