package com.kfcms.model;
// default package
// Generated Jul 27, 2014 11:32:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Game generated by hbm2java
 */
public class Game implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String account;
	private String name;
	private Date startTime;
	private String serverName;
	private String url;
	private String category;
	private String giftName;
	private String platform;
	/**
	 * 状态： 0 未审核 1  已审核 2 已锁定
	 */
	private Integer status;
	private Date gmtCreated;
	private Date gmtModified;
	
	public Game(){}
	
	public Game(String account, String name, Date startTime,
			String serverName, String url, String category, String giftName,
			String platform, Integer status, Date gmtCreated, Date gmtModified) {
		this.account = account;
		this.name = name;
		this.startTime = startTime;
		this.serverName = serverName;
		this.url = url;
		this.category = category;
		this.giftName = giftName;
		this.platform = platform;
		this.status = status;
		this.gmtCreated = gmtCreated;
		this.gmtModified = gmtModified;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getAccount() {
		return account;
	}
	public void setAccount(String account) {
		this.account = account;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Date getStartTime() {
		return startTime;
	}
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}
	public String getServerName() {
		return serverName;
	}
	public void setServerName(String serverName) {
		this.serverName = serverName;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public String getGiftName() {
		return giftName;
	}
	public void setGiftName(String giftName) {
		this.giftName = giftName;
	}
	public String getPlatform() {
		return platform;
	}
	public void setPlatform(String platform) {
		this.platform = platform;
	}
	public Integer getStatus() {
		return status;
	}
	public void setStatus(Integer status) {
		this.status = status;
	}
	public Date getGmtCreated() {
		return gmtCreated;
	}
	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}
	public Date getGmtModified() {
		return gmtModified;
	}
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
