package com.kfcms.model;
// default package
// Generated Jul 27, 2014 11:32:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String name;
	private String password;
	private String email;
	private Integer status;
	private String tel;
	private String qqmsn;
	private Date gmtCreated;
	private Date gmtModified;

	public User() {
	}

	public User(String name, String password, String email, Integer status,
			String tel, String qqmsn, Date gmtCreated, Date gmtModified) {
		this.name = name;
		this.password = password;
		this.email = email;
		this.status = status;
		this.tel = tel;
		this.qqmsn = qqmsn;
		this.gmtCreated = gmtCreated;
		this.gmtModified = gmtModified;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getQqmsn() {
		return this.qqmsn;
	}

	public void setQqmsn(String qqmsn) {
		this.qqmsn = qqmsn;
	}

	public Date getGmtCreated() {
		return this.gmtCreated;
	}

	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	public Date getGmtModified() {
		return this.gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

}
