package com.kfcms.model;
// default package
// Generated Jul 25, 2014 10:43:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer userId;
	private String userName;
	private String userPassword;
	private String userEmail;
	private String userTel;
	private String userQqmsn;
	private Date gmtCreated;
	private Date gmtModified;

	public User() {
	}

	public User(String userName, String userPassword, String userEmail,
			String userTel, String userQqmsn, Date gmtCreated, Date gmtModified) {
		this.userName = userName;
		this.userPassword = userPassword;
		this.userEmail = userEmail;
		this.userTel = userTel;
		this.userQqmsn = userQqmsn;
		this.gmtCreated = gmtCreated;
		this.gmtModified = gmtModified;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public String getUserTel() {
		return this.userTel;
	}

	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}

	public String getUserQqmsn() {
		return this.userQqmsn;
	}

	public void setUserQqmsn(String userQqmsn) {
		this.userQqmsn = userQqmsn;
	}

	public Date getGmtCreated() {
		return this.gmtCreated;
	}

	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	public Date getGmtModified() {
		return this.gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

}
